### ISSUE TITLE
Batching

### ISSUE THREAD

**Issue by robgil** [yaauie/logstash-filter-memcached-archived#1]
Batching may help improve performance. If batching 100 log messages at a time, we can potentially do a multi-get on the unique fields, then enrich the messages with the results.

Reference: https://groups.google.com/forum/#!topic/memcached/XIYlDaiPv_c

**Comment by yaauie** [comment]
Since this project has been moved to [logstash-plugins/logstash-filter-memcached](/logstash-plugins/logstash-filter-memcached), I have moved this feature request over there.
