### ISSUE TITLE
Stacking Requests / Responses - Async

### ISSUE THREAD

**Issue by robgil** [yaauie/logstash-filter-memcached-archived#2]
Is it possible for requests to stack and wait for responses asyncronously? I don't see anything in dalli, and they appear to rely on gunicorn to scale connections within a connection pool. 

Reference: https://groups.google.com/forum/#!topic/memcached/XIYlDaiPv_c

**Comment by yaauie** [comment]
@robgil no, this is not useful within Logstash; since `Filter#filter(event)` and `Filter#multi_filter(events)` are synchronous methods, it would not make sense to do work to make the single calls that happen within them asynchronous only to synchronise before returning.
